include_keywords:
  - "指数"
  - "A股"
  - "港股"
  - "美股"
  - "干细胞"
  - "创新药"
  - "BD交易"
  - "铂生"
  - "外泌体"
exclude_keywords:
  - "广告"
  - "推广"
  - "营销"
  - "优惠券"
  - "打折"
  - "促销"
  - "免费"
  - "赚钱"
  - "兼职"
